spring:
jpa:
  hibernate.ddl.auto: update
  database-platform: org.hibernate.dialect.H2Dialect
datasource:
  url: jdbc:h2:mem:checklist-app.db
  driver-class-name: org.h2.Driver
  username: sa
  password: 123
h2:
  console:
    path: /h2-console
